# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-03 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import egghunt.models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0002_auto_20170320_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField()),
                ('start_min', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.dropbox.DropBoxStorage(), upload_to=egghunt.models.random_filename),
        ),
    ]
