# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0003_auto_20180903_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='egg',
            name='longitude',
        ),
        migrations.AddField(
            model_name='egg',
            name='answer',
            field=models.CharField(default='abc', max_length=511),
            preserve_default=False,
        ),
    ]
