# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0004_auto_20200410_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=511)),
            ],
        ),
        migrations.RemoveField(
            model_name='egg',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='egg',
            name='radius_in_metres',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='answer',
            name='egg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egghunt.Egg'),
        ),
    ]
