# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import egghunt.models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0005_auto_20200410_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='abc123', storage=storages.backends.dropbox.DropBoxStorage(), upload_to=egghunt.models.random_filename),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='placement',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=511, primary_key=True, serialize=False),
        ),
    ]
