# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0007_egg_textclueafer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egg',
            old_name='textClueAfer',
            new_name='textClueAfter',
        ),
    ]
