# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egghunt', '0008_auto_20200412_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
